# Scraping Configuration
scraping:
  max_products: 10  # Maximum number of products to scrape
  wait_time: 2  # Time to wait between requests in seconds
  max_retries: 3  # Maximum number of retries for failed requests

# Browser Configuration
browser:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  headless: true  # Run browser in headless mode

# General Configuration
general:
  log_level: "INFO"
  timeout: 30  # Request timeout in seconds 