version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: shopify_scraper_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=shopify_scraper
    restart: unless-stopped

volumes:
  mongodb_data: 